In [2]:
import pandas as pd
import joblib

In [3]:
df = pd.read_csv(
    '../data/workforce_criticality.csv'
)

df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,EmployeeValueScore,ReplacementDifficulty,FinancialLoss,AttritionProbability,CriticalityScore,CriticalityLevel,ActionPriority
0,24,0,830,2,13,2,1,4,0,78,...,0,0,0,75.033,28,112198,0.167510,394.853325,Low,Monitor
1,44,2,1117,1,2,1,1,1,0,72,...,5,7,7,102.011,100,1012066,0.007939,819.631407,Low,Monitor
2,31,2,688,2,7,3,1,3,1,44,...,4,0,1,136.557,115,569342,0.213920,19126.570456,Medium,Review Within 30 Days
3,44,2,1199,1,4,2,1,3,1,92,...,9,14,13,204.190,303,2615140,0.002301,3723.290511,Low,Monitor
4,36,2,318,1,9,3,3,4,1,79,...,0,0,0,76.388,31,120328,0.484580,1380.761268,Low,Monitor

In [4]:
def recommend(row):

    rec = []

    if row['JobSatisfaction'] <= 2:
        rec.append(
            "Improve job satisfaction"
        )

    if row['WorkLifeBalance'] <= 2:
        rec.append(
            "Provide flexible work policy"
        )

    if row['StockOptionLevel'] == 0:
        rec.append(
            "Offer stock incentives"
        )

    if row['JobInvolvement'] <= 2:
        rec.append(
            "Increase employee engagement"
        )

    if row['EnvironmentSatisfaction'] <= 2:
        rec.append(
            "Improve work environment"
        )

    if row['OverTime'] == 1:
        rec.append(
            "Reduce overtime workload"
        )

    if row['MonthlyIncome'] < 5000:
        rec.append(
            "Consider salary adjustment"
        )

    if row['YearsSinceLastPromotion'] > 5:
        rec.append(
            "Provide promotion opportunity"
        )

    if len(rec) == 0:
        rec.append(
            "Maintain current retention strategy"
        )

    return rec

In [5]:
df['Recommendations'] = \
    df.apply(
        recommend,
        axis=1
    )

In [6]:
df[
    [
        'AttritionProbability',
        'CriticalityLevel',
        'Recommendations'
    ]
].head(20)

,AttritionProbability,CriticalityLevel,Recommendations
0,0.167510,Low,"[Improve job satisfaction, Consider salary adj..."
1,0.007939,Low,"[Improve work environment, Consider salary adj..."
2,0.213920,Medium,"[Provide flexible work policy, Increase employ..."
3,0.002301,Low,"[Improve job satisfaction, Provide flexible wo..."
4,0.484580,Low,"[Provide flexible work policy, Increase employ..."
5,0.283054,Medium,"[Provide flexible work policy, Offer stock inc..."
6,0.020826,Low,"[Offer stock incentives, Increase employee eng..."
7,0.009955,Low,"[Offer stock incentives, Increase employee eng..."
8,0.009208,Low,[Maintain current retention strategy]
9,0.340690,Low,"[Provide flexible work policy, Offer stock inc..."
10,0.123973,Medium,"[Offer stock incentives, Increase employee eng..."
11,0.107522,Medium,"[Increase employee engagement, Provide promoti..."
12,0.184870,Low,"[Improve job satisfaction, Offer stock incenti..."
13,0.215130,Critical,"[Increase employee engagement, Improve work en..."
14,0.137486,Low,"[Provide flexible work policy, Offer stock inc..."
15,0.529162,Low,"[Improve job satisfaction, Provide flexible wo..."
16,0.016243,Low,"[Improve job satisfaction, Improve work enviro..."
17,0.032093,Low,"[Increase employee engagement, Provide promoti..."
18,0.434567,Low,"[Provide flexible work policy, Offer stock inc..."
19,0.040871,Low,"[Increase employee engagement, Consider salary..."

In [7]:
df.to_csv(
    '../data/retention_recommendations.csv',
    index=False
)

In [8]:
def priority(row):

    if row['CriticalityLevel']=="Critical":
        return "Immediate Action"

    elif row['CriticalityLevel']=="Medium":
        return "Review Within 30 Days"

    return "Monitor"


df['ActionPriority'] = \
    df.apply(
        priority,
        axis=1
    )

In [9]:
def priority(row):

    if row['CriticalityLevel'] == "Critical":
        return "Immediate Action"

    elif row['CriticalityLevel'] == "Medium":
        return "Review Within 30 Days"

    return "Monitor"


df['ActionPriority'] = df.apply(
    priority,
    axis=1
)

print(df.columns)

df.to_csv(
    '../data/retention_recommendations.csv',
    index=False
)

Index(['Age', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'EmployeeValueScore', 'ReplacementDifficulty',
       'FinancialLoss', 'AttritionProbability', 'CriticalityScore',
       'CriticalityLevel', 'ActionPriority', 'Recommendations'],
      dtype='str')

In [10]:
test = pd.read_csv(
    '../data/retention_recommendations.csv'
)

print(
    test[
        [
            'CriticalityLevel',
            'ActionPriority'
        ]
    ].head()
)

  CriticalityLevel         ActionPriority
0              Low                Monitor
1              Low                Monitor
2           Medium  Review Within 30 Days
3              Low                Monitor
4              Low                Monitor